databases:
  - name: banking-postgres
    databaseName: bankdb
    user: admin
    plan: free

services:
  # 1. Transaction Service
  - type: web
    name: transaction-service
    plan: free
    env: docker
    dockerfilePath: Dockerfile.transaction
    envVars:
      - key: PORT
        value: 8082
      - key: DB_HOST
        fromDatabase:
          name: banking-postgres
          property: host
      - key: DB_PORT
        fromDatabase:
          name: banking-postgres
          property: port
      - key: DB_NAME
        fromDatabase:
          name: banking-postgres
          property: database
      - key: DB_USER
        fromDatabase:
          name: banking-postgres
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: banking-postgres
          property: password

  # 2. Account Service
  - type: web
    name: account-service
    plan: free
    env: docker
    dockerfilePath: Dockerfile.account
    envVars:
      - key: PORT
        value: 8081
      - key: TRANSACTION_URL
        value: http://transaction-service:8082/api/transactions
      - key: DB_HOST
        fromDatabase:
          name: banking-postgres
          property: host
      - key: DB_PORT
        fromDatabase:
          name: banking-postgres
          property: port
      - key: DB_NAME
        fromDatabase:
          name: banking-postgres
          property: database
      - key: DB_USER
        fromDatabase:
          name: banking-postgres
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: banking-postgres
          property: password

  # 3. API Gateway Nginx
  - type: web
    name: api-gateway
    plan: free
    env: docker
    dockerfilePath: Dockerfile.nginx
    envVars:
      - key: PORT
        value: 80
