worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    # Augmenter les timeouts pour le "cold start" (réveil) des services Render en version gratuite (ça prend souvent > 60s)
    proxy_connect_timeout 300s;
    proxy_send_timeout 300s;
    proxy_read_timeout 300s;

    server {
        listen       80;
        server_name  localhost;



        location / {
            return 200 'API Gateway is running';
            add_header Content-Type text/plain;
        }

        # Pas de résolveur Nginx nécessaire, le résolveur de l'OS sera utilisé au démarrage

        location /api/accounts {
            proxy_pass https://__ACCOUNT_SERVICE_HOST__;
            proxy_ssl_server_name on;
            proxy_set_header Host __ACCOUNT_SERVICE_HOST__;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /api/transactions {
            proxy_pass https://__TRANSACTION_SERVICE_HOST__;
            proxy_ssl_server_name on;
            proxy_set_header Host __TRANSACTION_SERVICE_HOST__;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
